export const GET_ARTICLES = 'GET_ARTICLES';

export const GET_ARTICLE = 'GET_ARTICLE';

export const ADD_ARTICLE = 'ADD_ARTICLE';

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const VALIDATION_FAILED = 'VALIDATION_FAILED';

export const CLEAR_VALIDATION_ERRORS = 'CLEAR_VALIDATION_ERRORS';

export const TOAST_MESSAGE = 'TOAST_MESSAGE';
